service: pbz-reports-service

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x

functions:
  resolveAccBalance:
    handler: handler.resolveAccBalance
